<?php
use \lenz\contentfield\helpers\debug\QueryInfo;
/** @var QueryInfo $query */
?>
<div class="tcfDebug--query">
  <h3 class="tcfDebug--queryTitle">
    <?php if ($query->type == QueryInfo::TYPE_ENTRY): ?>
      <svg width="24" height="24"><path d="M4 7V19H19V21H4C2 21 2 19 2 19V7H4M23 3V15C23 15 23 17 21 17H8C8 17 6 17 6 15V3H23M21 5H8V15H21V5M14 7H10V12H14V7M19 7H15V9H19V7M19 10H15V12H19V10Z" /></svg>
      <div>Entry query #<?php echo $query->index ?></div>
    <?php elseif ($query->type == QueryInfo::TYPE_ASSET): ?>
      <svg width="24" height="24"><path d="M21,17H7V3H21M21,1H7A2,2 0 0,0 5,3V17A2,2 0 0,0 7,19H21A2,2 0 0,0 23,17V3A2,2 0 0,0 21,1M3,5H1V21A2,2 0 0,0 3,23H19V21H3M15.96,10.29L13.21,13.83L11.25,11.47L8.5,15H19.5L15.96,10.29Z" /></svg>
      <div>Asset query #<?php echo $query->index ?></div>
    <?php else: ?>
      <svg width="24" height="24"><path d="M12,3C7.58,3 4,4.79 4,7C4,9.21 7.58,11 12,11C16.42,11 20,9.21 20,7C20,4.79 16.42,3 12,3M4,9V12C4,14.21 7.58,16 12,16C16.42,16 20,14.21 20,12V9C20,11.21 16.42,13 12,13C7.58,13 4,11.21 4,9M4,14V17C4,19.21 7.58,21 12,21C16.42,21 20,19.21 20,17V14C20,16.21 16.42,18 12,18C7.58,18 4,16.21 4,14Z" /></svg>
      <div>Query #<?php echo $query->index ?> (<?php echo $query->queryClass ?>)</div>
    <?php endif; ?>
  </h3>
  <div class="tcfDebug--queryContent row">
    <div class="col-md-6">
      <h4 class="tcfDebug--querySubtitle">Criteria</h4>
      <?php foreach ($query->criteria as $key => $value): ?>
        <dl class="tcfDebug--queryCriteria">
          <dt><?php echo $key; ?></dt>
          <dd><?php print_r($value); ?></dd>
        </dl>
      <?php endforeach; ?>
    </div>
    <div class="col-md-6">
      <h4 class="tcfDebug--querySubtitle">Backtrace <span onclick="this.parentElement.parentElement.classList.toggle('external');">Toggle external</span></h4>
      <ol class="tcfDebug--queryBacktrace">
        <?php echo implode('', array_map(function($data) {
          $content = [];
          $class = $data['type'] . ($data['external'] ? ' external' : '');
          $attributes = [
            'name'     => '<span class="name">%s</span>',
            'function' => '::<span class="function">%s</span>',
            'line'     => ' <span class="line">(%s)</span>'
          ];

          foreach ($attributes as $name => $template) {
            if (isset($data[$name]) && !empty($data[$name])) {
              $content[] = sprintf($template, $data[$name]);
            }
          }

          return \craft\helpers\Html::tag('li', implode('', $content), ['class' => $class]);
        }, $query->backtrace)); ?>
      </ol>
    </div>
  </div>
</div>
